version: '3'

services:
  # UI
  website:
    build: ./snowfox-website/target
    ports:
      - 5000:5000
    links:
      - product-service

  # PRODUCT
  product-service:
    build: ./snowfox-product/target
    ports:
      - 5001:5001

  # STOCK MANAGEMENT
  stock-service:
    build: ./snowfox-stock/target
    ports:
      - 5002:5002
    depends_on:
      - stock-redis
    links:
      - stock-redis

  stock-redis:
    image: redis:3.2.11-alpine
    ports:
      - 6379:6379

  zookeeper:
    image: zookeeper:3.4
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888 # server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.116 # localhost is not working in case of multiple brokers
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: stock:1:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # SEARCH
  search-service:
    build: ./snowfox-search/target
    ports:
      - 5003:5003

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
#    volumes:
#      - ./snowfox-infra/elasticsearch/config:/usr/share/elasticsearch/config
#      - ./snowfox-infra/elasticsearch/data:/usr/share/elasticsearch/data

#  kibana:
#    image: kibana:5.6.4
#    ports:
#      - 5601:5601

  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
